apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: devx-helloworld-springboot-5d6pc
    backstage.io/kubernetes-id: devx-helloworld-springboot-5d6pc
  name: devx-helloworld-springboot-5d6pc
  namespace: '{{ .Values.config.namespace }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devx-helloworld-springboot-5d6pc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devx-helloworld-springboot-5d6pc
    spec:
      containers:
      - image: 'vad1mo/hello-world-rest'
        imagePullPolicy: IfNotPresent
        name: devx-helloworld-springboot-5d6pc
        resources: {}
        ports:
          - containerPort: 5050 
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 5050
          periodSeconds: 5
status: {}
